/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package setting;

import java.awt.Color;
import java.awt.Toolkit;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import login.Login;

/**
 *
 * @author Administrator
 */
public class Setting extends javax.swing.JFrame {

    /**
     * Creates new form Setting
     */
    public Setting() {
        initComponents();
        logo();
          
        this.lbNama.setText(Login.getNamaUser().toUpperCase());
        this.lbNama.setHorizontalAlignment(JLabel.CENTER);
        this.lbNama.setVerticalAlignment(JLabel.CENTER);
        
        this.Nama.setText(Login.getNamaUser().toUpperCase());
        this.Nama.setHorizontalAlignment(JLabel.CENTER);
        this.Nama.setVerticalAlignment(JLabel.CENTER);
        
        this.tgl.setText(Login.getNamatgl().toUpperCase());
        this.tgl.setHorizontalAlignment(JLabel.CENTER);
        this.tgl.setVerticalAlignment(JLabel.CENTER);
        
        this.Jenis.setText(Login.getNamaJenis().toUpperCase());
        this.Jenis.setHorizontalAlignment(JLabel.CENTER);
        this.Jenis.setVerticalAlignment(JLabel.CENTER);
        
        this.no.setText(Login.getNo().toUpperCase());
        this.no.setHorizontalAlignment(JLabel.CENTER);
        this.no.setVerticalAlignment(JLabel.CENTER);
        
        this.alamat.setText(Login.getAlamat().toUpperCase());
        this.alamat.setHorizontalAlignment(JLabel.CENTER);
        this.alamat.setVerticalAlignment(JLabel.CENTER);
        
        this.btnAkun.setBackground(new Color (0,0,0,0));
         this.btnBarang.setBackground(new Color (0,0,0,0));
          this.btnHome.setBackground(new Color (0,0,0,0));
           this.btnInfo.setBackground(new Color (0,0,0,0));
            this.btnLogout.setBackground(new Color (0,0,0,0));
             this.btnSetting.setBackground(new Color (0,0,0,0));
              this.btnSupplier.setBackground(new Color (0,0,0,0));
               this.btnTransaksi.setBackground(new Color (0,0,0,0));
               
                 
    }
    private void logo() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("icon.png")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnSupplier = new javax.swing.JButton();
        btnBarang = new javax.swing.JButton();
        btnTransaksi = new javax.swing.JButton();
        btnSetting = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        btnAkun = new javax.swing.JButton();
        btnInfo = new javax.swing.JButton();
        btnHome = new javax.swing.JButton();
        tgl = new javax.swing.JLabel();
        Jenis = new javax.swing.JLabel();
        no = new javax.swing.JLabel();
        alamat = new javax.swing.JLabel();
        Nama = new javax.swing.JLabel();
        lbNama = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnSupplier.setBorder(null);
        btnSupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSupplierActionPerformed(evt);
            }
        });
        jPanel1.add(btnSupplier, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 170, 40));

        btnBarang.setBorder(null);
        btnBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBarangActionPerformed(evt);
            }
        });
        jPanel1.add(btnBarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 170, 40));

        btnTransaksi.setBorder(null);
        btnTransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTransaksiActionPerformed(evt);
            }
        });
        jPanel1.add(btnTransaksi, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 170, 40));

        btnSetting.setBorder(null);
        jPanel1.add(btnSetting, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, 170, 40));

        btnLogout.setBorder(null);
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });
        jPanel1.add(btnLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 450, 170, 40));

        btnAkun.setBorder(null);
        jPanel1.add(btnAkun, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 40, 70, 60));

        btnInfo.setBorder(null);
        btnInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInfoActionPerformed(evt);
            }
        });
        jPanel1.add(btnInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 40, 70, 60));

        btnHome.setBorder(null);
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });
        jPanel1.add(btnHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 170, 40));

        tgl.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jPanel1.add(tgl, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 260, 190, 30));

        Jenis.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jPanel1.add(Jenis, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 180, 190, 30));

        no.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jPanel1.add(no, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 260, 190, 30));

        alamat.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jPanel1.add(alamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 340, 190, 30));

        Nama.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jPanel1.add(Nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 180, 190, 30));

        lbNama.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jPanel1.add(lbNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 160, 20));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/figma/6. Menu Setting akhir.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        int status;
        status = JOptionPane.showConfirmDialog(this, "Apakah anda yakin ingin keluar ?", "confirm", JOptionPane.YES_OPTION, JOptionPane.QUESTION_MESSAGE);
        switch (status){
            case JOptionPane.YES_OPTION:
                this.setVisible(false);
                new login.Login().setVisible(true);
                break;
        }
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        this.setVisible(false);
        new menuUtama.dasboard().setVisible(true);
    }//GEN-LAST:event_btnHomeActionPerformed

    private void btnSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSupplierActionPerformed
        this.setVisible(false);
        new menuSupplier.menusupplier().setVisible(true);
    }//GEN-LAST:event_btnSupplierActionPerformed

    private void btnBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBarangActionPerformed
        this.setVisible(false);
        new Barang.menubarang().setVisible(true);
    }//GEN-LAST:event_btnBarangActionPerformed

    private void btnTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTransaksiActionPerformed
        this.setVisible(false);
        new menuTransaksi.TransaksiUtama().setVisible(true);
    }//GEN-LAST:event_btnTransaksiActionPerformed

    private void btnInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInfoActionPerformed
         this.setVisible(false);
        new setting.setInfo().setVisible(true);
    }//GEN-LAST:event_btnInfoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Setting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Setting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Setting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Setting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Setting().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Jenis;
    private javax.swing.JLabel Nama;
    private javax.swing.JLabel alamat;
    private javax.swing.JButton btnAkun;
    private javax.swing.JButton btnBarang;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnInfo;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnSetting;
    private javax.swing.JButton btnSupplier;
    private javax.swing.JButton btnTransaksi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbNama;
    private javax.swing.JLabel no;
    private javax.swing.JLabel tgl;
    // End of variables declaration//GEN-END:variables
}
