/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package login;

import menuUtama.dasboard;
import java.awt.Color;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import static login.Koneksi.configDB;

/**
 *
 * @author Windows 11
 */
public class Login extends javax.swing.JFrame {
    Connection con;
//    Statement stat;
    ResultSet rs;
    String sql;
// deklrasi akun
    public static String USERNAME = "";
    public static String TGLLAHIR = "";
    public static String JENIS = "";
    public static String NOHP = "";
    public static String ALAMAT = "";
    public static String NAMA = "";
   
    
    public Login() {
        initComponents();
        logo();
        
        this.btnLupa.setBackground(new Color (0,0,0,0));
        this.btnLogin.setBackground(new Color(0,0,0,0));
        this.btnRegister1.setBackground(new Color(0,0,0,0));
        this.btnShow.setBackground(new Color(0,0,0,0));
        this.txtPass.setBackground(new Color(0,0,0,0));
        this.txtUser.setBackground(new Color(0,0,0,0));
        this.btnShow.setVisible(false);
        this.btnHide.setBackground(new Color(0,0,0,0));
    }

                
        
    //  untuk menampilkan nama di dasboard
     public static String getNamaUser(){
        return USERNAME;
  
    }
     public static String getNamatgl(){
        return TGLLAHIR;
    }
     public static String getNamaJenis(){
        return JENIS;
    }
     public static String getNo(){
        return NOHP;
    }
     public static String getAlamat(){
        return ALAMAT;
    }
     
     private void logo() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("icon.png")));
    }
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnLogin = new javax.swing.JButton();
        btnRegister1 = new javax.swing.JButton();
        txtUser = new javax.swing.JTextField();
        btnShow = new javax.swing.JButton();
        txtPass = new javax.swing.JPasswordField();
        btnHide = new javax.swing.JButton();
        btnLupa = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        jPanel1.add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 310, 170, 60));

        btnRegister1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegister1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegister1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, 170, 60));

        txtUser.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtUser.setBorder(null);
        jPanel1.add(txtUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, 360, 50));

        btnShow.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/figma/Invisible.png"))); // NOI18N
        btnShow.setBorder(null);
        btnShow.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnShowMousePressed(evt);
            }
        });
        btnShow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowActionPerformed(evt);
            }
        });
        jPanel1.add(btnShow, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 220, 40, 50));

        txtPass.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtPass.setBorder(null);
        txtPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPassActionPerformed(evt);
            }
        });
        txtPass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPassKeyPressed(evt);
            }
        });
        jPanel1.add(txtPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, 280, 50));

        btnHide.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/figma/Vector (2).png"))); // NOI18N
        btnHide.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnHideMousePressed(evt);
            }
        });
        jPanel1.add(btnHide, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 220, 40, 50));

        btnLupa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLupaActionPerformed(evt);
            }
        });
        jPanel1.add(btnLupa, new org.netbeans.lib.awtextra.AbsoluteConstraints(143, 280, 140, 20));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/figma/2. Login akhir.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnHideMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHideMousePressed
        btnShow.setVisible(true);
        btnHide.setVisible(false);
        txtPass.setEchoChar((char)0);
    }//GEN-LAST:event_btnHideMousePressed

    private void btnShowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnShowActionPerformed

    private void btnShowMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnShowMousePressed
        btnShow.setVisible(false);
        btnHide.setVisible(true);
        txtPass.setEchoChar('*');
    }//GEN-LAST:event_btnShowMousePressed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
       
        try {
            txtUser.requestFocus();
             java.sql.Connection conn=(Connection)Koneksi.configDB();
           java.sql.Statement stat = conn.createStatement();
            ResultSet result=stat.executeQuery ("select * from akun where "
                + "username='" +txtUser.getText()+"'");
            if (result.next()) {
                if (txtPass.getText().equals(result.getString("password"))){
                    USERNAME = result.getString("nama");
                    TGLLAHIR = result.getString("tgl_lahir");
                    JENIS = result.getString("jenis_kelamin");
                    NOHP = result.getString("no_telp");
                    ALAMAT = result.getString("alamat");
                    JOptionPane.showMessageDialog(rootPane, "Anda Berhasil Login ");
                    dasboard mn = new dasboard();
                    mn.setVisible(true);
                    this.dispose();
                } else {
                    JOptionPane.showMessageDialog(rootPane,"Wrong Password");
                    txtPass.setText("");
                    txtUser.requestFocus();
                }
            } else {
                JOptionPane.showMessageDialog(rootPane, "User Not Found");
                txtUser.setText("");
                txtPass.setText("");
                txtUser.requestFocus();
            }
        } catch (Exception e){
            e.printStackTrace();
            JOptionPane.showMessageDialog(rootPane, "Fail");
        }               
    }//GEN-LAST:event_btnLoginActionPerformed

    private void btnRegister1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegister1ActionPerformed
       this.setVisible(false);
       new register().setVisible(true);
    }//GEN-LAST:event_btnRegister1ActionPerformed

    private void btnLupaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLupaActionPerformed
        this.setVisible(false);
        new lupapassword().setVisible(true);
    }//GEN-LAST:event_btnLupaActionPerformed

    private void txtPassKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPassKeyPressed
         if (evt.getKeyCode()== KeyEvent.VK_ENTER){
            btnLoginActionPerformed(new ActionEvent(evt.getSource(), evt.getID(), "Data Berhasil di tambahkan"));
        }
    }//GEN-LAST:event_txtPassKeyPressed

    private void txtPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPassActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                    new Login().setVisible(true);
          
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHide;
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnLupa;
    private javax.swing.JButton btnRegister1;
    private javax.swing.JButton btnShow;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField txtPass;
    private javax.swing.JTextField txtUser;
    // End of variables declaration//GEN-END:variables
}
