/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package login;

import java.awt.Color;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author Administrator
 */
public class lupapassword extends javax.swing.JFrame {

    /**
     * Creates new form lupapassword
     */
    public lupapassword() {
        initComponents();
        logo();
        this.btnShow.setVisible(false);
        
        this.txtNohp.setBackground(new Color (0,0,0,0));
         this.txtPass.setBackground( new Color (0,0,0,0));
          this.txtUser.setBackground( new Color (0,0,0,0));
           this.btnKembali.setBackground( new Color (0,0,0,0));
            this.btnLanjut.setBackground( new Color (0,0,0,0));
            this.btnShow.setVisible(false);
            this.btnShow.setBackground(new Color (0,0,0,0));
            this.btnHide.setBackground(new Color (0,0,0,0));
    }
    
     private boolean cekUserKontak() {
        try {
            String sql = "SELECT username, no_telp FROM akun WHERE username = '" + txtUser.getText() + "' AND no_telp = '" + txtNohp.getText() + "'";
            Connection c = (Connection) Koneksi.configDB();
            Statement s = c.createStatement();
            ResultSet r = s.executeQuery(sql);

            if (r.next()) {
                return true;
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }
        return false;
    }
            
            
     
     private void logo() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("icon.png")));
    }
     
     public void filterAngka(KeyEvent a){
        if(Character.isAlphabetic(a.getKeyChar())){
            a.consume();
           
        } else{
        
        }
    }
    
    public void filterChar(KeyEvent a){
        if(!Character.isLetterOrDigit(a.getKeyChar())){
            a.consume();
           
        } else{
        
        }
    }
     


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtUser = new javax.swing.JTextField();
        btnKembali = new javax.swing.JButton();
        btnLanjut = new javax.swing.JButton();
        txtNohp = new javax.swing.JTextField();
        btnShow = new javax.swing.JButton();
        btnHide = new javax.swing.JButton();
        txtPass = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtUser.setBorder(null);
        jPanel1.add(txtUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 140, 170, 30));

        btnKembali.setBorder(null);
        btnKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKembaliActionPerformed(evt);
            }
        });
        jPanel1.add(btnKembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 340, 160, 50));

        btnLanjut.setBorder(null);
        btnLanjut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLanjutActionPerformed(evt);
            }
        });
        jPanel1.add(btnLanjut, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 340, 160, 50));

        txtNohp.setBorder(null);
        txtNohp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNohpActionPerformed(evt);
            }
        });
        txtNohp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNohpKeyTyped(evt);
            }
        });
        jPanel1.add(txtNohp, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 200, 180, 30));

        btnShow.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/figma/merem.png"))); // NOI18N
        btnShow.setBorder(null);
        btnShow.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnShowMousePressed(evt);
            }
        });
        jPanel1.add(btnShow, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 260, 30, 30));

        btnHide.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/figma/mata (1).png"))); // NOI18N
        btnHide.setBorder(null);
        btnHide.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnHideMousePressed(evt);
            }
        });
        jPanel1.add(btnHide, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 260, 30, 30));

        txtPass.setBorder(null);
        txtPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPassActionPerformed(evt);
            }
        });
        txtPass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPassKeyTyped(evt);
            }
        });
        jPanel1.add(txtPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 260, 140, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/figma/lupa password (1).png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembaliActionPerformed
        this.setVisible(false);
        new Login().setVisible(true);
    }//GEN-LAST:event_btnKembaliActionPerformed

    private void btnLanjutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLanjutActionPerformed
         if (txtUser.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Username Harus Di isi");
        } else if (txtPass.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Password Baru Harus Di isi");
        } else if (txtNohp.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Nomer Kontak Harus Di isi");
        } else {

            if (this.cekUserKontak()) {
                String sql = "UPDATE akun Set password = '" + txtPass.getText() + "' WHERE username = '" 
                        + txtUser.getText() + "'";

                    
                try {
                    Connection c = (Connection) Koneksi.configDB();
                    Statement s = c.createStatement();

                    if (JOptionPane.showConfirmDialog(null, "Apakah data yang dimasukan telah sesuai?", "WARNING",
                            JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
                        int res = s.executeUpdate(sql);
                        JOptionPane.showMessageDialog(null, "Password Berhasil Diganti");
                        this.setVisible(false);
                        new Login().setVisible(true);
                        
                        
                        
                    }
                 
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, "Password Gagal Diganti"+e);
                        
                    
                }
                    }else
                     JOptionPane.showMessageDialog(null, "Password Gagal Diganti");
            {
                
            
            }
        }
                    
                       

                    
    }//GEN-LAST:event_btnLanjutActionPerformed

    private void btnHideMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHideMousePressed
        btnShow.setVisible(true);
        btnHide.setVisible(false);
        txtPass.setEchoChar((char)0);
    }//GEN-LAST:event_btnHideMousePressed

    private void btnShowMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnShowMousePressed
        btnShow.setVisible(false);
        btnHide.setVisible(true);
        txtPass.setEchoChar('*');
    }//GEN-LAST:event_btnShowMousePressed

    private void txtPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPassActionPerformed

    private void txtPassKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPassKeyTyped
        
    }//GEN-LAST:event_txtPassKeyTyped

    private void txtNohpKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNohpKeyTyped
         this.filterAngka(evt);
        this.filterChar(evt);
    }//GEN-LAST:event_txtNohpKeyTyped

    private void txtNohpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNohpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNohpActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(lupapassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(lupapassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(lupapassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(lupapassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new lupapassword().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHide;
    private javax.swing.JButton btnKembali;
    private javax.swing.JButton btnLanjut;
    private javax.swing.JButton btnShow;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtNohp;
    private javax.swing.JPasswordField txtPass;
    private javax.swing.JTextField txtUser;
    // End of variables declaration//GEN-END:variables
}
