
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package login;

import java.awt.Color;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import static login.Koneksi.configDB;


/**
 *
 * @author Administrator
 */
public class register extends javax.swing.JFrame {
    
     
    /**
     * Creates new form register
     */
    public static String nama;
    public static String username;
    public static String password;
    public register() {
        initComponents();
        kosong();
        logo();
        idotomatis();
        
        this.btnShow.setVisible(false);
       this.txtgender.setEditable(false);
       
        this.btnDaftar.setBackground(new Color(0,0,0,0));
          this.btnRefresh.setBackground(new Color(0,0,0,0));
            this.btnKembali.setBackground(new Color(0,0,0,0));
              this.txtNama.setBackground(new Color(0,0,0,0));
                this.txtUsername.setBackground(new Color(0,0,0,0));
                  this.txtPass.setBackground(new Color(0,0,0,0));
                      this.txtNotlpn.setBackground(new Color(0,0,0,0));
                        this.txtAlamat.setBackground(new Color(0,0,0,0));
                          this.date.setBackground(new Color(0,0,0,0));
                           this.gender.setBackground(new Color (0,0,0,0));
                            this.btnShow.setBackground(new Color (0,0,0,0));
                            this.btnHide.setBackground(new Color (0,0,0,0));
                            
        
                           
    }
    private void kosong(){
        txtNama.setText(null);
        txtUsername.setText(null);
        txtPass.setText(null);
        date.setDate(null);
        txtNotlpn.setText(null);
        txtAlamat.setText(null);
    }
    
     private void idotomatis(){
           try{
            Connection c = Koneksi.configDB();
            Statement s = c.createStatement();
            String sql = "SELECT * FROM akun ORDER BY id_akun DESC";
            ResultSet r = s.executeQuery(sql);
            if (r.next()) {
                String NoFaktur = r.getString("id_akun").substring(2);
                String B = "" +(Integer.parseInt(NoFaktur)+1);
                String Nol = "";
                
                if(B.length()==1)
                {Nol = "000";}
                else if(B.length()==2)
                {Nol = "00";}
                else if(B.length()==3)
                {Nol = "0";}
                else if(B.length()==4)
                {Nol = "";}
                txtidAkun.setText("A" + Nol + B);
            }else{      
                txtidAkun.setText("A0001");
            } 
            r.close();
            s.close();  
        }catch (Exception e) { 
            System.out.println("autonumber eror");
        }
       }
     
     private void logo() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("icon.png")));
    }
    
     public void filterAngka(KeyEvent a){
        if(Character.isAlphabetic(a.getKeyChar())){
            a.consume();
           
        } else{
        
        }
    }
    
    public void filterChar(KeyEvent a){
        if(!Character.isLetterOrDigit(a.getKeyChar())){
            a.consume();
           
        } else{
        
        }
    }
                    
  


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnDaftar = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();
        btnKembali = new javax.swing.JButton();
        txtUsername = new javax.swing.JTextField();
        txtNotlpn = new javax.swing.JTextField();
        txtAlamat = new javax.swing.JTextField();
        txtNama = new javax.swing.JTextField();
        txtgender = new javax.swing.JTextField();
        gender = new javax.swing.JComboBox<>();
        btnShow = new javax.swing.JButton();
        btnHide = new javax.swing.JButton();
        txtPass = new javax.swing.JPasswordField();
        date = new com.toedter.calendar.JDateChooser();
        indikator = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtidAkun = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("REGISTER");
        setUndecorated(true);
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnDaftar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDaftarActionPerformed(evt);
            }
        });
        jPanel1.add(btnDaftar, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 370, 110, 30));

        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });
        jPanel1.add(btnRefresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 370, 30, 30));

        btnKembali.setBorder(null);
        btnKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKembaliActionPerformed(evt);
            }
        });
        jPanel1.add(btnKembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 370, 100, 30));

        txtUsername.setBorder(null);
        jPanel1.add(txtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 130, 160, 30));

        txtNotlpn.setBorder(null);
        txtNotlpn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNotlpnKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNotlpnKeyTyped(evt);
            }
        });
        jPanel1.add(txtNotlpn, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 280, 170, 40));

        txtAlamat.setBorder(null);
        jPanel1.add(txtAlamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 320, 170, 40));

        txtNama.setBorder(null);
        jPanel1.add(txtNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 90, 160, 30));

        txtgender.setBorder(null);
        jPanel1.add(txtgender, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 250, 150, 30));

        gender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Laki-laki", "Perempuan" }));
        gender.setBorder(null);
        gender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genderActionPerformed(evt);
            }
        });
        jPanel1.add(gender, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 250, 170, 30));

        btnShow.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/figma/merem.png"))); // NOI18N
        btnShow.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnShowMousePressed(evt);
            }
        });
        btnShow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowActionPerformed(evt);
            }
        });
        btnShow.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnShowKeyPressed(evt);
            }
        });
        jPanel1.add(btnShow, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 170, 30, 30));

        btnHide.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/figma/mata (1).png"))); // NOI18N
        btnHide.setBorder(null);
        btnHide.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnHideMousePressed(evt);
            }
        });
        btnHide.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnHideKeyPressed(evt);
            }
        });
        jPanel1.add(btnHide, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 170, 30, 30));

        txtPass.setText("jPasswordField1");
        txtPass.setBorder(null);
        txtPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPassActionPerformed(evt);
            }
        });
        txtPass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPassKeyReleased(evt);
            }
        });
        jPanel1.add(txtPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 170, 130, 30));
        jPanel1.add(date, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 210, 170, 30));

        indikator.setBackground(new java.awt.Color(0, 0, 0));
        indikator.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jPanel1.add(indikator, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 174, 60, 20));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/figma/1. Register enyar.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        txtidAkun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtidAkunActionPerformed(evt);
            }
        });
        jPanel1.add(txtidAkun, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, 80, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        kosong();
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void btnKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembaliActionPerformed
         if (JOptionPane.showConfirmDialog(null, "Jika anda keluar data yang anda masukkan akan hilang ?", "WARNING",
            JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {  
        new Login().setVisible(true);
        this.dispose();
        } else {
       }
    }//GEN-LAST:event_btnKembaliActionPerformed

    private void btnDaftarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDaftarActionPerformed
     if(txtNama.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Nama Harus Di isi");
        }else if(txtUsername.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Username Harus Di isi");
        } else if (txtPass.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Password Harus Di isi");
        } else if (date.getDate().equals("")){
            JOptionPane.showMessageDialog(null, "Tanggal Lahir Harus Di isi");
        } else if (txtgender.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Jenis Kelamin Harus Di isi");
        } else if (txtNotlpn.getText().equals("")){
            JOptionPane.showMessageDialog(null, "No Hp Harus Di isi");      
        } else if  (txtAlamat.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Alamat Harus Di isi");
        } else if (this.txtNotlpn.getText().length()<12){
            JOptionPane.showMessageDialog(this, "No Telpn min 12 digit");
        } else if (this.txtNotlpn.getText().length()>13){
            JOptionPane.showMessageDialog(this, "No Telpn max 13 digit");
        }else if (this.txtPass.getText().length()<6){  
            JOptionPane.showMessageDialog(this,"Password min 6 karakter");
        }else if (this.txtPass.getText().length()>10){
            JOptionPane.showMessageDialog(null,"Password max 10 karakter");
        }else{    
            
       
        
     
         String tanggalahir = "yyyy-MM-dd";
         SimpleDateFormat fm = new SimpleDateFormat(tanggalahir);
         String tanggal = String.valueOf(fm.format(date.getDate()));
         String sql = "insert into akun values (?,?,?,?,?,?,?,?)";
         
         
         try {
            java.sql.Connection conn=(Connection) Koneksi.configDB();
            java.sql.PreparedStatement stat=conn.prepareStatement(sql);
            stat.setString(1, txtidAkun.getText());
            stat.setString(2, txtNama.getText());
            stat.setString(3, txtUsername.getText ());
            stat.setString(4, txtPass.getText());
            stat.setString(5, tanggal);
            stat.setString(6,txtgender.getText());
            stat.setString(7, txtNotlpn.getText());
            stat.setString(8, txtAlamat.getText());
            if (JOptionPane.showConfirmDialog(null, "Apakah data yang dimasukan telah sesuai?", "WARNING",
            JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {     
                 stat.executeUpdate();
                 JOptionPane.showMessageDialog(null, "Akun Berhasil Dibuat");
                 kosong();
                 this.setVisible(false);
                 new Login().setVisible(true);
            } else {
        }
       txtNama.requestFocus(); 
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Akun Gagal Dibuat"+e);
        }
         idotomatis();
     }
         
         
    }//GEN-LAST:event_btnDaftarActionPerformed

    private void genderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genderActionPerformed
        switch(gender.getSelectedIndex()){
            case 0:
                    txtgender.setText("Laki - Laki");
                    break;   
            case 1:
                    txtgender.setText("Perempuan");
                    break;   
    }                     
    }//GEN-LAST:event_genderActionPerformed

    private void btnShowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnShowActionPerformed

    private void btnShowKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnShowKeyPressed
        
    }//GEN-LAST:event_btnShowKeyPressed

    private void btnHideKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnHideKeyPressed
      
    }//GEN-LAST:event_btnHideKeyPressed

    private void btnShowMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnShowMousePressed
        btnShow.setVisible(false);
        btnHide.setVisible(true);
        txtPass.setEchoChar('*');
    }//GEN-LAST:event_btnShowMousePressed

    private void btnHideMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHideMousePressed
         btnShow.setVisible(true);
        btnHide.setVisible(false);
        txtPass.setEchoChar((char)0);
    }//GEN-LAST:event_btnHideMousePressed

    private void txtidAkunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidAkunActionPerformed
      idotomatis();        
    }//GEN-LAST:event_txtidAkunActionPerformed

    private void txtNotlpnKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNotlpnKeyReleased
     
       
    }//GEN-LAST:event_txtNotlpnKeyReleased

    private void txtNotlpnKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNotlpnKeyTyped
        this.filterAngka(evt);
        this.filterChar(evt);
    }//GEN-LAST:event_txtNotlpnKeyTyped

    private void txtPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPassActionPerformed
 static String hasnumber;
    private void txtPassKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPassKeyReleased
        // untuk indikator password 
        String password=this.txtPass.getText();
        char[] chars = password.toCharArray();
        hasnumber ="";
        for(char c: chars ){
            if(Character.isDigit(c)){
            hasnumber = "yes";
        }
        }
        
        if(password.length() > 10 &&!password.equals(password.toLowerCase())&&hasnumber.equals("yes")){
            this.indikator.setText("KUAT");
            indikator.setForeground(Color.pink);
        }else if(this.txtPass.getText().length()>8){
            this.indikator.setText("KUAT");
            indikator.setForeground(Color.GREEN);
        }else if(this.txtPass.getText().length()>6){
            this.indikator.setText("SEDANG");
            indikator.setForeground(Color.blue);
        }else{
            this.indikator.setText("LEMAH");
            indikator.setForeground(Color.red);
        }
    }//GEN-LAST:event_txtPassKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDaftar;
    private javax.swing.JButton btnHide;
    private javax.swing.JButton btnKembali;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnShow;
    private com.toedter.calendar.JDateChooser date;
    private javax.swing.JComboBox<String> gender;
    private javax.swing.JLabel indikator;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtAlamat;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtNotlpn;
    private javax.swing.JPasswordField txtPass;
    private javax.swing.JTextField txtUsername;
    private javax.swing.JTextField txtgender;
    private javax.swing.JTextField txtidAkun;
    // End of variables declaration//GEN-END:variables
}
